version: "3.7"

services:
  # Matic Redis instance.
  availapi-redis:
    image: redis:6.2.4-alpine
    container_name: redis.local2
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 50

  availapi:
    build: ./
    container_name: availapi
    ports:
      - 5000:8000
    depends_on:
      - availapi-redis

  availapi-tests:
    build: 
      context: ./
      dockerfile: Dockerfile.test
    container_name: availapi-tests
    depends_on:
      - availapi-redis

networks:
  default:
    name: availapi-api-network
