version: "3.7"

services:
  # Matic Redis instance.
  availapi-redis:
    image: redis:6.2.4-alpine
    container_name: redis.local2
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 50

  availapi-api:
    build: ./
    container_name: availapi-api
    ports:
      - 5000:8000
    depends_on:
      - availapi-redis

networks:
  default:
    name: availapi-api-network
